<a href="https://colab.research.google.com/github/wily037/www.ameyodataminds.co.ke/blob/main/Introduction_to_machine_learning_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
#single dimensional array
Array1=np.array([1,2,3,4])
#print(Array1)
# 2-dimensional array
Array2=np.array([[1,2,3],[4,5,6]])
#print(Array2)
#3-dimensional array
Array3=np.array([[[1,2,3],[4,5,6],[6,7,8]]])
print(Array3)
# Indexing of arrays
#print(Array3[0,0,0])
#print(Array3[0,1,2])
#print(Array3[0,2,2])
print(Array3[0,1,2])
# PROPERTIES OF ARRAYS
print(Array3.ndim)
# the shape of the array
print(Array3.shape)
#The number of elements in the array
print(Array3.size)
#the size of storage space required to store the array
print(Array3.nbytes)
print(Array3.dtype)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]]
6
3
(1, 3, 3)
9
72
int64
